[tox]
envlist = lint
skipsdist = true

[testenv:lint]
deps =
    ruff
    black
    flake8

allowlist_externals =
    ruff
    black
    flake8

commands =
    ruff check --fix check_codes
    black --include ".*[.]pyi?$" check_codes
    flake8 check_codes